// src/components/react/todo.tsx
import Display from './display';
import Icon from './icon';
import Input from './input';

export default (): React.ReactElement => (
  <>
    <div className='fixed animate-float shadow-none top-1/3 left-[80%]'>
      <Icon />
    </div>
    <div className='flex flex-col h-full'>
      <div className='flex-grow overflow-x-auto'>
        <Display />
      </div>
      <Input />
    </div>
  </>
);

// src/components/vue/todo.vue
<script setup lang="ts">
import Display from './display.vue';
import Icon from './icon.vue';
import Input from './input.vue';
</script>

<template>
  <div class="fixed animate-float shadow-none top-20 left-[60%] md:top-1/3 md:left-[80%]">
    <Icon />
  </div>
  <div class="flex flex-col h-full">
    <div class="flex-grow overflow-x-auto">
      <Display />
    </div>
    <Input />
  </div>
</template>
